name: Build Backstage Image

on:
  workflow_dispatch:

env:
  APP_DOMAIN: ${{ vars.APP_DOMAIN }}
  DOCKER_IMAGE_TAG: ${{ vars.DOCKER_IMAGE_TAG }}
  VERSION: ${{ vars.DOCKER_IMAGE_TAG }}
  NODE_OPTIONS: ${{ vars.NODE_OPTIONS }}
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: ${{ vars.BUCKET_NAME }}
  GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
  AUTH_GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID }}
  AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}

jobs:
  tf_deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan