name: Deploy Infrastructure

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
  TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
  TF_VAR_github_token: ${{ secrets.AUTH_GITHUB_TOKEN }}
  TF_VAR_github_client_id: ${{ secrets.AUTH_GITHUB_CLIENT_ID }}
  TF_VAR_github_client_secret: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}
  TF_VAR_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  tf_deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan